config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  resources :products do
    collection do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
    end
    member do
      get 'get_category_children', defaults: { format: 'json' }
      get 'get_category_grandchildren', defaults: { format: 'json' }
      post 'purchase'
      get 'buy'
    end
  end
  devise_for :users, controllers: {
    sessions: 'users/sessions'
  }
  resources :users, only: %i[show edit update]
  get '/mypage' => 'users#mypage'
  root to: 'products#index'
end

app/views/shared/_footer.html.erb
 <footer class="main-footer">
     <div class="foot">
         <strong>Copyright ◎2022 <a href=<%= products_path %>>KIRAIBAR</a>.</strong> All rights reserved.
 </footer>

app/views/shared/_header.html.erb
<div class='pc'>
    <ul class='navbar'>
        <li><%= link_to t('views.header.home'),products_path %></li>
        <% if user_signed_in? %>
        <li><%= link_to t('views.header.product'), new_product_path %></li>
        <li><%= link_to t('views.header.mypage'), user_path(current_user.id) %></li>
        <li><%= link_to t('views.header.logout'), destroy_user_session_path, method: :delete %></li>
        <% else %>
        <li><%= link_to t('views.header.sign_in'), new_user_registration_path %></li>
        <li> <%= link_to t('views.header.login'), new_user_session_path %></li>
        <% end %>
        <%# <%= form_with url: products_path, method: :get, local: true do |form| %>
        <%# <%= form.select("label_id", Label.pluck(:genre, :id), { include_blank: true }) %>
        <%# <%= form.submit 'ジャンル別検索', name: nil %></li>
        <%# <% end %>
        </li>
    </ul>
</div>